/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsideHeader: typeof import('./src/components/headBar/AsideHeader.vue')['default']
    DailyTitle: typeof import('./src/components/headBar/DailyTitle.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTree: typeof import('element-plus/es')['ElTree']
    FileList: typeof import('./src/components/FileList.vue')['default']
    GuidedConfiguration: typeof import('./src/components/GuidedConfiguration.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    MiniAction: typeof import('./src/components/headBar/MiniAction.vue')['default']
    SaveButton: typeof import('./src/components/headBar/SaveButton.vue')['default']
    SystemButton: typeof import('./src/components/SystemButton.vue')['default']
  }
}
